### **Task 2:  Sentiment Analysis using NLP Pipeline & ML Models**

In [5]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\prajy\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\prajy\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\prajy\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\prajy\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\prajy\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\prajy\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [6]:
# Basic Libraries
import numpy as np
import pandas as pd

# NLP Libraries
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Sklearn Libraries
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\prajy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\prajy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [16]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [17]:
# Shape
print("Dataset Shape:", df.shape)

# Class distribution
print("\nClass Distribution:\n", df['sentiment'].value_counts())

# Sample data
df.sample(5)

Dataset Shape: (50000, 2)

Class Distribution:
 sentiment
positive    25000
negative    25000
Name: count, dtype: int64

                                                  review sentiment
41554  I don't quite get the rating for The Amati Gir...  negative
15307  This was the first PPV in a new era for the WW...  positive
38267  haha! you have to just smile and smile if you ...  negative
38479  This is a VERY bad movie. However, I read that...  negative
21128  This film is not deserved of the next few minu...  negative

In [18]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # Lowercase
    text = text.lower()
    
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    
    # Remove special characters & numbers
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    
    # Tokenization
    tokens = text.split()
    
    # Remove stopwords & Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    
    return " ".join(tokens)

In [19]:
df['cleaned_review'] = df['review'].apply(preprocess_text)

df[['review', 'cleaned_review']].head()

,review,cleaned_review
0,One of the other reviewers has mentioned that ...,one reviewer mentioned watching oz episode hoo...
1,A wonderful little production. <br /><br />The...,wonderful little production br br filming tech...
2,I thought this was a wonderful way to spend ti...,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,basically family little boy jake think zombie ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter mattei love time money visually stunnin...

In [20]:
df['sentiment'] = df['sentiment'].map({'positive':1, 'negative':0})